export const Books = [
    {
      id: 1,
      title: "Dune",
      pageCount: 688,
      publishedDate: "1965-08-01",
      coverImage: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSt7xlJEzb-xopDqcQ6iw9SbY8PAlJN8H7DYUzTqmZkwLT9o8JXv6YWvDMGRKwkyRnf6RHzGg",
      description: "A legendary Sci-Fi novel exploring politics, religion, and humanity on the desert planet Arrakis.",
      status: "PUBLISH",
      author: "Frank Herbert",
      categories: ["Sci-Fi"],
      rating:"4"
    },
    {
      id: 2,
      title: "The Martian",
      pageCount: 387,
      publishedDate: "2014-02-11",
      coverImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1cn6i1-z0X-18P7UKD-admBcUorkh6pxUMkOXyje--nxlWJllwJOsTY8mViygwg0dt56Odg",
      description: "A gripping tale of survival about an astronaut stranded on Mars.",
      status: "PUBLISH",
      author: "Andy Weir",
      categories: ["Sci-Fi"],
      rating:"4.5"
    },
    {
      id: 3,
      title: "Pride and Prejudice",
      pageCount: 279,
      publishedDate: "1813-01-28",
      coverImage: "https://m.media-amazon.com/images/M/MV5BMTA1NDQ3NTcyOTNeQTJeQWpwZ15BbWU3MDA0MzA4MzE@._V1_.jpg",
      description: "A timeless romance novel about love and societal expectations.",
      status: "PUBLISH",
      author: "Jane Austen",
      categories: ["Romance"],
      rating:"3.4"
    },
    {
      id: 4,
      title: "To Kill a Mockingbird",
      pageCount: 324,
      publishedDate: "1960-07-11",
      coverImage: "https://cdn.britannica.com/21/182021-050-666DB6B1/book-cover-To-Kill-a-Mockingbird-many-1961.jpg",
      description: "A powerful tale of race, morality, and justice in the American South.",
      status: "PUBLISH",
      author: "Harper Lee",
      categories: ["Fiction"],
      rating:"4.2"
    },
    {
      id: 5,
      title: "Sapiens: A Brief History of Humankind",
      pageCount: 498,
      publishedDate: "2011-09-04",
      coverImage: "https://m.media-amazon.com/images/I/713jIoMO3UL._AC_UY218_.jpg",
      description: "A groundbreaking exploration of humanity's history and impact on the world.",
      status: "PUBLISH",
      author: "Yuval Noah Harari",
      categories: ["Non-Fiction"],
      rating:"4"
    },
    {
      id: 6,
      title: "1984",
      pageCount: 328,
      publishedDate: "1949-06-08",
      coverImage: "https://m.media-amazon.com/images/I/71rpa1-kyvL.jpg",
      description: "A dystopian novel about surveillance and the struggle for freedom.",
      status: "PUBLISH",
      author: "George Orwell",
      categories: ["Fiction"],
      rating:"4.3"
    },
    {
      id: 7,
      title: "The Notebook",
      pageCount: 214,
      publishedDate: "1996-10-01",
      coverImage: "https://m.media-amazon.com/images/M/MV5BZjE0ZjgzMzYtMTAxYi00NGMzLThmZDktNzFlMzA2MWRmYWQ0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
      description: "A deeply emotional story of enduring love and memories.",
      status: "PUBLISH",
      author: "Nicholas Sparks",
      categories: ["Romance"],
      rating:"5"
    },
    {
      id: 8,
      title: "Educated",
      pageCount: 334,
      publishedDate: "2018-02-20",
      coverImage: "https://m.media-amazon.com/images/I/81WojUxbbFL._AC_UY218_.jpg",
      description: "A memoir of resilience and the transformative power of education.",
      status: "PUBLISH",
      author: "Tara Westover",
      categories: ["Non-Fiction"],
      rating:"4"
    },
    {
      id: 9,
      title: "Foundation",
      pageCount: 244,
      publishedDate: "1951-06-01",
      coverImage: "https://m.media-amazon.com/images/I/81LT+V9G4IL._AC_UF1000,1000_QL80_.jpg",
      description: "A seminal Sci-Fi series about the fall and rise of civilizations.",
      status: "PUBLISH",
      author: "Isaac Asimov",
      categories: ["Sci-Fi"],
      rating:"3.4"
    },
    {
      id: 10,
      title: "Jane Eyre",
      pageCount: 500,
      publishedDate: "1847-10-16",
      coverImage: "https://m.media-amazon.com/images/M/MV5BZWYwMGE1YTItYjdhZS00YWRjLTg4YjMtZGFmMTY2M2RmZjAyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
      description: "A romance novel about independence, morality, and true love.",
      status: "PUBLISH",
      author: "Charlotte Brontë",
      categories: ["Romance"],
      rating:"4"
    },
    {
      id: 11,
      title: "Becoming",
      pageCount: 448,
      publishedDate: "2018-11-13",
      coverImage: "https://m.media-amazon.com/images/I/81h2gWPTYJL._AC_UY218_.jpg",
      description: "A deeply personal memoir by Michelle Obama, chronicling her life journey.",
      status: "PUBLISH",
      author: "Michelle Obama",
      categories: ["Non-Fiction"],
      rating:"4.1"
    },
    {
      id: 12,
      title: "Brave New World",
      pageCount: 268,
      publishedDate: "1932-01-01",
      coverImage: "https://m.media-amazon.com/images/I/91D4YvdC0dL._AC_UF1000,1000_QL80_.jpg",
      description: "A dystopian classic exploring a controlled, engineered society.",
      status: "PUBLISH",
      author: "Aldous Huxley",
      categories: ["Fiction"],
      rating:"4"
    },
    {
      id: 13,
      title: "The Fault in Our Stars",
      pageCount: 313,
      publishedDate: "2012-01-10",
      coverImage: "https://m.media-amazon.com/images/M/MV5BYTA4ODg5YWUtYmZiYy00Y2M4LWE0NjEtODE5MzhkYmJmZGEwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
      description: "A heart-wrenching romance story about love and loss.",
      status: "PUBLISH",
      author: "John Green",
      categories: ["Romance"],
      rating:"5"
    },
    {
      id: 14,
      title: "The Immortal Life of Henrietta Lacks",
      pageCount: 381,
      publishedDate: "2010-02-02",
      coverImage: "https://m.media-amazon.com/images/M/MV5BMTA3MzA2NzkxMzleQTJeQWpwZ15BbWU4MDAxNDE1NzEy._V1_.jpg",
      description: "The true story of an African American woman whose cells changed medicine forever.",
      status: "PUBLISH",
      author: "Rebecca Skloot",
      categories: ["Non-Fiction"],
      rating:"4"
    },
    {
      id: 15,
      title: "Hyperion",
      pageCount: 482,
      publishedDate: "1989-05-26",
      coverImage: "https://upload.wikimedia.org/wikipedia/en/7/73/Hyperion_cover.jpg",
      description: "A stunning Sci-Fi epic about humanity, mystery, and exploration.",
      status: "PUBLISH",
      author: "Dan Simmons",
      categories: ["Sci-Fi"],
      rating:"4"
    },
    {
      id: 16,
      title: "Gone with the Wind",
      pageCount: 1037,
      publishedDate: "1936-06-30",
      coverImage: "https://m.media-amazon.com/images/I/612gOvRX85L._AC_UF1000,1000_QL80_.jpg",
      description: "A sweeping romance set against the backdrop of the Civil War.",
      status: "PUBLISH",
      author: "Margaret Mitchell",
      categories: ["Romance"],
      rating:"3"
    },
    {
      id: 17,
      title: "A Brief History of Time",
      pageCount: 212,
      publishedDate: "1988-03-01",
      coverImage: "https://m.media-amazon.com/images/I/81DBK93b6jL.jpg",
      description: "Stephen Hawking's exploration of the universe, time, and black holes.",
      status: "PUBLISH",
      author: "Stephen Hawking",
      categories: ["Non-Fiction"],
      rating:"4.6"
    },
    {
      id: 18,
      title: "Frankenstein",
      pageCount: 280,
      publishedDate: "1818-01-01",
      coverImage: "https://m.media-amazon.com/images/I/81FzMSO3XnL._UF1000,1000_QL80_.jpg",
      description: "A Gothic masterpiece blending horror and science fiction.",
      status: "PUBLISH",
      author: "Mary Shelley",
      categories: ["Fiction"],
      rating:"4"
    },
    {
      id: 19,
      title: "The Time Traveler's Wife",
      pageCount: 546,
      publishedDate: "2003-07-05",
      coverImage: "https://m.media-amazon.com/images/M/MV5BMDE3MTNlNTAtMWIxNC00NGYyLTlmODUtZWE3ODRkZDljZjUzXkEyXkFqcGc@._V1_.jpg",
      description: "A unique romance story about time travel and love's endurance.",
      status: "PUBLISH",
      author: "Audrey Niffenegger",
      categories: ["Romance"],
      rating:"4"
    },
    {
      id: 20,
      title: "The Wright Brothers",
      pageCount: 320,
      publishedDate: "2015-05-05",
      coverImage: "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781471150371/wright-brothers-9781471150371_hr.jpg",
      description: "The story of the aviation pioneers who changed the world forever.",
      status: "PUBLISH",
      author: "David McCullough",
      categories: ["Non-Fiction"],
      rating:"5"
    },
    {
      id: 21,
      title: "Harry Potter and the Sorcerer’s Stone",
      pageCount: 309,
      publishedDate: "1997-06-26",
      coverImage: "https://m.media-amazon.com/images/I/81YOuOGFCJL._AC_UY218_.jpg",
      description: "The first book in the Harry Potter series, following Harry’s discovery of the wizarding world.",
      status: "PUBLISH",
      author: "J.K. Rowling",
      categories: ["Fantasy"],
      rating: "4.9"
    },
    {
      id: 22,
      title: "The Hobbit",
      pageCount: 310,
      publishedDate: "1937-09-21",
      coverImage: "https://m.media-amazon.com/images/I/91b0C2YNSrL._AC_UY218_.jpg",
      description: "A fantasy adventure about Bilbo Baggins’ journey with dwarves to reclaim their homeland.",
      status: "PUBLISH",
      author: "J.R.R. Tolkien",
      categories: ["Fantasy"],
      rating: "4.8"
    },
    {
      id: 23,
      title: "The Name of the Wind",
      pageCount: 662,
      publishedDate: "2007-03-27",
      coverImage: "https://m.media-amazon.com/images/I/81m1s4wIPML._AC_UY218_.jpg",
      description: "The tale of Kvothe, a gifted young man growing up to become a legend.",
      status: "PUBLISH",
      author: "Patrick Rothfuss",
      categories: ["Fantasy"],
      rating: "4.7"
    },
    {
      id: 24,
      title: "Sherlock Holmes: A Study in Scarlet",
      pageCount: 188,
      publishedDate: "1887-11-01",
      coverImage: "https://rukminim2.flixcart.com/image/850/1000/xif0q/book/j/a/e/a-study-in-scarlet-a-sherlock-holmes-adventure-original-imagmyhvf8h4cphk.jpeg?q=90&crop=false",
      description: "The first Sherlock Holmes novel, introducing the famous detective and his methods.",
      status: "PUBLISH",
      author: "Arthur Conan Doyle",
      categories: ["Mystery"],
      rating: "4.5"
    },
    {
      id: 25,
      title: "Gone Girl",
      pageCount: 422,
      publishedDate: "2012-05-24",
      coverImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_9Wmf7wrNUi2cEw97buXQznfnNR788FZ7tA&s",
      description: "A psychological thriller about a woman’s mysterious disappearance and the secrets that unfold.",
      status: "PUBLISH",
      author: "Gillian Flynn",
      categories: ["Mystery"],
      rating: "4.6"
    }
  ];
  